### ISSUE TITLE
Investigation: search for an alternative to the singleton design pattern for the ServiceProvider

### ISSUE THREAD

**Issue by kevto** [sevarac/VisualRecognitionApi#16]
The ServiceProvider is a singleton and we'd like to investigate if there's an alternative to the singleton design pattern.

**Comment by keilw** [comment]
You may want to have a look at the [ServiceProvider](https://github.com/unitsofmeasurement/unit-api/blob/master/src/main/java/javax/measure/spi/ServiceProvider.java) of JSR 363/385.

Most importantly, it shall not be in an "internal" package (which Jigsaw won't expose) but something like "spi" or similar. While `current()` also returns the one that's active at a time, `available()` returns a list of all available service providers in the classpath. JSR 363 makes use of that already, e.g. extension modules like SI or other Unit systems add their own `ServiceProvider`.

**Comment by kevto** [comment]
Thanks for the suggestion, I think it'd be better to adopt a similar method of DI which is also used in other standardised specifications (the JSR's you mentioned), regardless, my implementation of DI has been really educational.

**Comment by kevto** [comment]
@keilw I removed our current ServiceProvider and started again from scratch. I used your ServiceProvider for inspiration and looks very similar now (even without copy+paste). Would you like to be mentioned in the JavaDoc as you can barely spot the differences? And if it okay to use your approach of the ServiceProvider in the first place?

The ServiceProvider and usage of it is much more elegant as @fgreco55 mentioned as well. We're really greatful for the feedback and I hope to merge my local code with the master branch later this week.

**Comment by keilw** [comment]
@kevto @fgreco55 Thanks a lot, I'd be happy if you mentioned us, also don't forget @desruisseaux please, he helped quite a bit with the simplification of the `ServiceProvider`. Based on e.g. JSR 382 where many contributors of e.g. patterns and inspirations in other projects like DeltaSpike are mentioned, it seems a good idea to do the same here.

**Comment by kevto** [comment]
Merged by #20
