### ISSUE TITLE
Separate repositories

### ISSUE THREAD

**Issue by keilw** [sevarac/VisualRecognitionApi#19]
API/Spec, TCK and RI should be in their own independent repositories, take examples like

- [JSR 107](https://github.com/jsr107)
- [JSR 354](https://github.com/JavaMoney)
- [JSR 363/385](https://github.com/unitsofmeasurement)

[JSR 382](https://github.com/eclipse/ConfigJSR) is among the few where API/Spec and TCK share the same repository. While this sounds legitimate (**NOT the RI**) it adds some problems especially when parts like the API or TCK need to be maintained or improved independently and the version changes. Would you then force a redeploy of all the other parts for no reason?

**Comment by kevto** [comment]
That sounds problematic indeed. Thanks for yet another suggestion :) ! I will bring this up in the next meeting tomorrow evening.

**Comment by kevto** [comment]
@sevarac I was thinking of creating a GitHub organisation (without additional subscriptions) and move the api repository to the GitHub organisation. Then I'd suggest to create a TCK and RI repository as well, similarly to other JSR's. 

A suggestion on the GitHub organisation name and repository names:
- JavaVisRec/visrec-api (or JavaVisRec/visrec-spec)
- JavaVisRec/visrec-tck
- JavaVisRec/visrec-ri

**Comment by kevto** [comment]
@sevarac I sent you an invite to become a part of the GitHub organisation. I will transfer the ownership to you once you accepted your invite. 

This repository is also imported in the organisation.
